### ISSUE TITLE
Module not found: Error: Default condition should be last one

### ISSUE THREAD

**Issue by valentin-kaiser** [juanelas/pbkdf2-hmac#13]
After upgrading the pbkdf2-hmac library from version 1.1.0 to 1.2.0, I started encountering Angular compilation errors that seem unrelated to the library itself. The error messages are cryptic and do not point to a specific issue in the Angular application. 

```
ERROR in ./src/app/pages/login/login.page.ts 15:0-37
Module not found: Error: Default condition should be last one
ModuleNotFoundError: Module not found: Error: Default condition should be last one
```

The line to which the error points is a blank line.

These errors occur in several components and seem to be related to the imports. The error message "Default condition should be last one" is not a standard Angular error and might be related to a custom loader or plugin used in the project.

The issue appears only when the pbkdf2-hmac library is updated to version 1.2.0. Reverting to version 1.1.0 resolves the compilation errors.

Steps to reproduce:

    Upgrade the pbkdf2-hmac library to version 1.2.0 in an Angular project.
    Run ng build or ng serve.

Expected behavior:
The Angular application should compile without any errors related to the pbkdf2-hmac library update.

Actual behavior:
The Angular application fails to compile, throwing cryptic error messages related to imports in several components.

Environment:

    Angular version: 15.2.4
    Node.js version: 19.9.0
    npm version: 9.6.3
    pbkdf2-hmac version: 1.2.0
    Operating System: Windows 11

I would appreciate any help in resolving this issue or understanding why the library update causes these errors.

**Comment by juanelas** [comment]
My apologies for that! It should be fixed. Please update to version 1.2.1, and thank you for reporting the issue!

**Comment by valentin-kaiser** [comment]
Works wonderfully. Thank you for the quick fix.
